### ISSUE TITLE
make output of list-packages more user friendly

### ISSUE THREAD

**Issue by hoijui** [tvo/rapid#2]
ideas:
- sort it
- allow to filter out all revision tags

related:
- allow pinning of tags through regex, for example: `rapid pin-regex ".*:latest"`

**Comment by tvo** [comment]
Thanks for the suggestion! :-)

Sorting shall be in some version.

Filtering out all revision tags isn't easy, as rapid doesn't know about revision tags. That's just a convention that's currently used on the servers.

Just pinning through regex seems a bit inconsistent, I'll consider adding an option to turn all "search queries" into regexes.
(Should be easier now I finally refactored it to use the optparse module ;-))

**Comment by hoijui** [comment]
.. sounds good :-)
do you think it would make sense to extend the protocol to make tags taggable? ( :D )
as in: revisionTag, stableTag, testingTag
would be cool to have tag-tags, no? :D

maybe it would be enough to just have one marker, like "spam", which would be set on revisions only, and rely on conventions for the rest (stable, latest, ...).

... or rely on a convention for revisions too, and try to get all project maintainers to use the same scheme (CA's "revision:1234" seems good there, though it relies on SVN). That would work well if you manage to do the all-search-is-regex thing.

May talk to Licho or det.

**Comment by hoijui** [comment]
.. just talked to det, he already figured out this to be a problem already, and wants to talk to you and Licho about a change.

**Comment by tvo** [comment]
Ok, I'll speak to them.

**Comment by tvo** [comment]
Note to self: spoke to det, seems whatever he suggested wouldn't have a really big impact on rapid. Advised to go for single file approach for transactional integrity.

Waiting now for det/Licho to communicate final implementation.

**Comment by tvo** [comment]
sorting done in 5cbbab5e8ddf0e28733b7fdf04d49b81da9b7fd5

**Comment by tvo** [comment]
add -r/--regex option to use regex instead of substring matches

Should work for all commands that take a searchterm.
(*pin, *install, list*, etc.)

The regexes are case insensitive and not anchored by default.
(Use ^ and $ to anchor to begin and end of string respectively.)

Example: `rapid -r list-tags '^(?!ba).*:(latest|stable|test)$'`
This displays all tags ending with ':latest', ':stable' or ':test',
which do not start with the string 'ba'.

Closed by 348235a127b5afce01fabdf8b52bff6f9544909c

**Comment by hoijui** [comment]
perfect!, including the regex example. :D
