### ISSUE TITLE
rapid-spring-latest-win32.7z on springrts.com misses zlib1.dll+MSVCR71.dll

### ISSUE THREAD

**Issue by abma** [tvo/rapid#21]
these files are required to run rapid.exe/rapid-gui.exe

who maintains the windows build? i can't find info about that...

**Comment by tvo** [comment]
Actually I'm not sure either. hoijui generally asked [me] to put a new rapid in place, but probably koshi created the archive. Or maybe aegis did that... I think koshi though.

**Comment by abma** [comment]
hm, then i'm unsure who i should ask:

can you please repack the current file and add zlib1.dll+MSVCR71.dll?

( https://github.com/spring/mingwlibs/tree/master/dll )

**Comment by renefritze** [comment]
yeah I did. I maintain a cxx_freeze branch on my rapid repo from which I create the binaries. That script does not however copy all mandatory dlls apparently, yet I get no error running them in my vm. As for for repacking, just ask someone (lurker,licho for example) with server access to do it directly on disk imo.

**Comment by abma** [comment]
on a fresh installed system, without any developer-libs installed, you get error about these missing files, when spring is put into a subdir of spring. (as already discussed here: http://springrts.com/phpbb/viewtopic.php?f=12&t=25266 )

i put it repacked there: http://springfiles.com/spring/spring-base/rapid-downloader

**Comment by tvo** [comment]
I put it on springrts.com and pointed the rapid-spring-latest-win32.7z symlink to that file. Is there any way we can automatically test for this failure? (probably not...)
