### ISSUE TITLE
win32 build of rapid doesn't work with unitsync of spring-master

### ISSUE THREAD

**Issue by abma** [tvo/rapid#23]
rapid pin ba:latest
[...]
[unitsync] initialized, 0.82+.4.0 (0.82.3-1597-ge28e19d Headless Unitsync)
[unitsync] joining
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27
, in <module>
  File "bin/rapid", line 7, in <module>
  File "Z:\python\rapid\rapid\ui\text\main.py", line 117, in main
  File "Z:\python\rapid\rapid\unitsync\api.py", line 83, in get_writable_data_di
rectory
  File "Z:\python\rapid\rapid\unitsync\unitsync.py", line 183, in Init
ValueError: Procedure probably called with not enough arguments (4 bytes missing
)

**Comment by abma** [comment]
this was: http://springrts.com/dl/rapid-spring-0.5.2-rc1-dllfix-win32.7z

**Comment by tvo** [comment]
That appears to be because this [unitsync-API-breaking-change](https://github.com/spring/spring/commit/d15bbf47ad93e9e68179a0394596a9ebccefa0f1) is still in master.

Was it already decided we want to keep that or is it going to be reverted? (For now I assume the last as I vaguely recall thats what we did in the release branch.)

**Comment by abma** [comment]
i don't know... i added it to the topics for the next meeting.

afaik rene milk is springlobby dev and this commit comes from him... so i think its better to keep it, this logging messages anoy since years :)

**Comment by renefritze** [comment]
That is my commit, yes, and I tought this was reverted entirely because of the fail wrt default values I wasn't aware of.

**Comment by abma** [comment]
hm, so maybe just add a InitLib function + mark Init as deprecated (+ remove somewhen in future?) or add a config setting to disable logging?

**Comment by renefritze** [comment]
Fine by me, but tbh I've since forgotten what use the unitsync silencing had.

**Comment by abma** [comment]
i reverted the commit, now it works again :)

(imo silencing is to not confuse users :)

**Comment by abma** [comment]
https://github.com/spring/spring/commit/c69ad84a55e41677400eeb0dd4cd785c42de0245
