### ISSUE TITLE
rapid prefers C:\Program Files\Spring\unitsync.dll over ..\unitsync.dll

### ISSUE THREAD

**Issue by abma** [tvo/rapid#26]
when spring is installed twice: stable in C:\Program Files\Spring\unitsync.dll and
c:\temp\spring

and c:\temp\spring\rapid\rapid.exe is run, the unitsync in program files is used.

**Comment by abma** [comment]
best would be, to support the newly registry-key, but i'm unsure if that makes sense/is possible in python.

(HKLM\Software\Spring\SpringEngineHelper points directly to unitsync)

**Comment by tvo** [comment]
Should be possible, I suppose I can add that to the searched locations.

For the regkey-not-present case I can swap the order in which Program Files and . and .. are searched.

**Comment by abma** [comment]
so.. imo order should be (mostly because of portable installs):

current path
parent path
reg key
(if still needed? program files)

i hope i didn't miss something

**Comment by tvo** [comment]
Here you can see where it looks and in which order:

https://github.com/tvo/rapid/blob/master/rapid/unitsync/api.py#L30

On 1 April 2011 12:03, abma
reply@reply.github.com
wrote:

**Comment by tvo** [comment]
Maybe you can try this code at some point and see what it prints:

```
import os
if os.name == 'nt':
    import _winreg
    try:
        key = _winreg.OpenKey(_winreg.HKEY_LOCAL_MACHINE, r'Software\Spring')
        value, type = _winreg.QueryValueEx(key, r'SpringEngineHelper')
        _winreg.CloseKey(key)
        if type == _winreg.REG_SZ:
            print value
        else:
            print 'key of unknown type'
    except _winreg.WindowsError as e:
        print e
```

**Comment by abma** [comment]
seems to work: prints c:\programme\spring\unitsync.dll

if the key doesn't exist i get:

AttributeError: module object has no attribute 'WindowsError'

when modified except _winreg.WindowsError as e to
    except WindowsError as e:

it prints "The System cannot find the specified File"

**Comment by tvo** [comment]
Great, thanks!

I will integrate this asap.

On 7 April 2011 17:43, abma
reply@reply.github.com
wrote:

**Comment by tvo** [comment]
Thanks for integrating it!
