### ISSUE TITLE
man pages missing

### ISSUE THREAD

**Issue by jandd** [tvo/rapid#4]
I'm about to package rapid for Debian (see http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=593330). rapid does not come with man pages for rapid and rapid-gui. It would be nice if you could provide rapid.6 and rapid-gui.6 in section Games.

I could create stub man pages using help2man if you like.

**Comment by jandd** [comment]
I have manpages for rapid and rapid-gui ready at http://github.com/jandd/rapid/commit/1de688330278751af25134353ded2e85fab7d4b2

**Comment by tvo** [comment]
Fixed in v0.3.3, thanks for the patch!

Maybe when I've more time I'll see if I can somehow generate man pages from the readme automatically. Trying to keeping documentation up to date in many places only guarantees it will get out of date in some places.
