### ISSUE TITLE
Allow for a automatic yes option

### ISSUE THREAD

**Issue by ScarylePoo** [tvo/rapid#8]
So that when running a clean upgrade, any questions answered are automatically answered as a yes.

**Comment by tvo** [comment]
Good point, easy to implement.

(Create subclass of `TextUserInteraction` and override `confirm` to always return True. Then link this to a commandline argument -y / --yes.)

**Comment by tvo** [comment]
added -y/--yes option to skip confirmations

Closed by 5b51d67412a66f378aead72ff8468aa51db6aa47

**Comment by ScarylePoo** [comment]
Thanks Tobi!
